import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Headphones, ShieldCheck, Truck } from 'lucide-react';
import { StoreHeader } from '@/components/store/store-header';
import { getStorefrontData } from '@/server/storefront';

const omr = new Intl.NumberFormat('en-OM', { style: 'currency', currency: 'OMR', minimumFractionDigits: 3 });

export default async function Home() {
  const { categories, products, announcement } = await getStorefrontData();
  return <main id="main-content" className="min-h-screen overflow-x-hidden bg-[#03060c] text-white">
    <a href="#main-content" className="sr-only z-50 rounded-lg bg-cyan-300 px-4 py-3 font-bold text-[#04101b] focus:not-sr-only focus:fixed focus:left-4 focus:top-4">Skip to main content</a>
    {announcement ? <a href={announcement.link ?? '#featured'} className="block bg-cyan-300 px-4 py-2.5 text-center text-sm font-bold text-[#04101b] hover:bg-cyan-200">{announcement.textEn}</a> : null}
    <StoreHeader categories={categories} />
    <section className="relative isolate border-b border-white/10"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_75%_40%,rgba(23,186,224,.17),transparent_32%),linear-gradient(135deg,#040812_0%,#091523_55%,#04101a_100%)]" /><div className="mx-auto grid min-h-[580px] max-w-[1440px] items-center gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[1.2fr_.8fr] lg:px-8"><div className="max-w-3xl"><p className="mb-5 text-sm font-black uppercase tracking-[.28em] text-cyan-300">Built for Oman. Ready for battle.</p><h1 className="text-balance text-5xl font-black leading-[.95] tracking-[-.05em] sm:text-7xl xl:text-8xl">Own the game.<br /><span className="text-cyan-300">Build without limits.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-300">Performance gaming PCs, precision components, and serious gear—selected for players who refuse to compromise.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="#featured" className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-cyan-300 px-6 py-3 font-black text-[#04101b] shadow-[0_0_24px_rgba(34,211,238,.22)] hover:bg-cyan-200">Shop featured <ArrowRight className="size-4" /></Link><Link href="/build" className="inline-flex min-h-12 items-center rounded-xl border border-white/15 bg-white/5 px-6 py-3 font-bold hover:border-cyan-300/50 hover:bg-white/10">Build your PC</Link></div></div><div className="relative mx-auto w-full max-w-md"><div className="absolute inset-8 rounded-full bg-cyan-400/15 blur-3xl" /><Image src="/blackshark-logo.png" alt="BLACKSHARK BS Gaming emblem" width={512} height={512} priority className="relative w-full rounded-[2rem] border border-cyan-300/20 shadow-2xl" /></div></div></section>
    <section aria-labelledby="category-title" className="mx-auto max-w-[1440px] px-4 py-16 sm:px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-[.2em] text-cyan-300">Find your advantage</p><h2 id="category-title" className="mt-2 text-3xl font-black sm:text-4xl">Shop by department</h2><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{categories.map((category, index) => <Link key={category.id} href={`/categories/${category.slug}`} className="group min-h-36 rounded-2xl border border-white/10 bg-[#0a111d] p-5 transition hover:-translate-y-1 hover:border-cyan-300/40"><span className="text-xs font-black text-cyan-300">0{index + 1}</span><h3 className="mt-10 text-lg font-bold group-hover:text-cyan-200">{category.nameEn}</h3><span className="mt-2 block text-sm text-slate-500">Explore products</span></Link>)}</div></section>
    <section id="featured" aria-labelledby="featured-title" className="scroll-mt-32 border-y border-white/10 bg-[#07101a]"><div className="mx-auto max-w-[1440px] px-4 py-16 sm:px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-[.2em] text-cyan-300">Staff picks</p><h2 id="featured-title" className="mt-2 text-balance text-3xl font-black sm:text-4xl">Featured Performance Gear</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{products.map((product) => <article key={product.id} className="overflow-hidden rounded-2xl border border-white/10 bg-[#0b1420]"><div className="grid aspect-square place-items-center bg-gradient-to-br from-[#101d2c] to-[#060b12]"><Image src={product.imageKey ?? '/blackshark-logo.png'} alt="" width={220} height={220} className="h-3/5 w-3/5 rounded-2xl object-cover opacity-90" /></div><div className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-cyan-300">{product.sku}</p><h3 className="mt-2 min-h-12 break-words font-bold">{product.titleEn}</h3><p className="mt-4 text-xl font-black tabular-nums">{omr.format((product.salePriceBaisa ?? product.priceBaisa) / 1000)}</p><p className="mt-2 text-sm text-emerald-300">{product.stockQuantity > 0 ? `${product.stockQuantity} in stock` : 'Out of stock'}</p><Link href={`/products/${product.slug}`} className="mt-5 inline-flex min-h-11 w-full items-center justify-center rounded-xl bg-white/8 px-4 font-bold hover:bg-cyan-300 hover:text-[#04101b]">View Product</Link></div></article>)}</div></div></section>
    <section aria-label="Store benefits" className="mx-auto grid max-w-[1440px] gap-4 px-4 py-14 sm:grid-cols-3 sm:px-6 lg:px-8">{[[Truck,'Fast GCC delivery','Clear delivery estimates across Oman and the GCC.'],[ShieldCheck,'Protected purchases','Secure checkout architecture and genuine warranty details.'],[Headphones,'Real support','Helpful local support before and after your purchase.']].map(([Icon,title,copy]) => { const BenefitIcon = Icon as typeof Truck; return <div key={String(title)} className="flex gap-4 rounded-2xl border border-white/10 p-5"><BenefitIcon className="mt-1 size-6 shrink-0 text-cyan-300" /><div><h2 className="font-bold">{String(title)}</h2><p className="mt-1 text-sm leading-6 text-slate-400">{String(copy)}</p></div></div>})}</section>
    <footer className="border-t border-white/10 px-4 py-8 text-center text-sm text-slate-500">© 2026 BLACKSHARK. Built for players across Oman and the GCC.</footer>
  </main>;
}
